# In .travis.yml

language: python
python:
  - "3.8"

before_install:
  - nvm install 12.10
install:
  - pip install -r requirements.txt
  - npm install -g serverless
  - npm install
script: 
  - serverless deploy

